print("(こんにちは世界) is how you say Hello World in (japanese).")
print("(Γειά σου Κόσμε) is how you say Hello World in (greek).")
print("(Olá Mundo) is how you say Hello World in (portugese).")
print("(Ahoj světe) is how you say Hello World in (czech).")
print("(안녕 세상) is how you say Hello World in (korean).")
print("(你好，世界) is how you say Hello World in (chinese).")
