print("Row "*3 + "your boat")
print("Gently down the stream.")
print("Merrily "*4)
print("Life is but a dream.")
print()
print()
print("And I was like")
print("Baby")
print("oooooooh!")
print("Baby")
print("nooooooo!")
